export default [
    {gov:"Ariana", 
    cities :[  "Ariana"	,
        	    "Soukra",
                "Raoued",
                "Kalâat el-Andalous",
                "Sidi Thabet",
                "Ettadhamen-Mnihla"]
            },
    {gov:"Beja", 
    cities:[    "AMDOUN",
                "BEJA NORD",
                "BEJA SUD",
                "GOUBELLAT",
                "MEJEZ EL BAB",
                "NEFZA",
                "TEBOURSOUK",
                "TESTOUR",
                "THIBAR"
            ]},
    {gov:"Ben Arous", 
    cities:["BEN AROUS",
                "BOU MHEL",
                "EL MOUROUJ",
                "EZZAHRA",
                "FOUCHANA",
                "HAMMAM CHATT",
                "HAMMAM LIF",
                "MEGRINE",
                "MOHAMADIA",
                "MORNAG",
                "NOUVELLE MEDINA",
                "RADES"
                ]},
        {gov:"Bizerte", 
        cities:[     "BIZERTE NORD",
                        "BIZERTE SUD",
                        "EL ALIA",
                        "GHAR EL MELH",
                        "GHEZALA",
                        "JOUMINE",
                        "MATEUR",
                        "MENZEL BOURGUIBA",
                        "MENZEL JEMIL",
                        "RAS JEBEL",
                        "SEJNANE",
                        "TINJA",
                        "UTIQUE",
                        "ZARZOUNA"
            ]},
    {gov:"Gabès", 
    cities:[   "DKHILET TOUJANE",
                "EL HAMMA",
                "GABES MEDINA",
                "GABES OUEST",
                "GABES SUD",
                "GHANNOUCHE",
                "MARETH",
                "MATMATA",
                "MENZEL HABIB",
                "METOUIA",
                "NOUVELLE MATMATA"
            ]},
   {gov: "Gafsa", 
   cities:[]},
    {gov:"Jendouba", 
    cities:[]},
    {gov:"Kairouan", 
    cities:[]},
    {gov:"Kasserine", 
    cities:[]},
    {gov:"Kébili", 
    cities:[]},
    {gov:"Kef", 
    cities:[]},
   {gov:"Mahdia", 
   cities:[]},
   {gov:"Manouba", 
   cities:[  "BORJ EL AMRI",
                "DOUAR HICHER",
                "EL BATTAN",
                "JEDAIDA",
                "LA MANNOUBA",
                "MORNAGUIA",
                "OUED ELLIL",
                "TEBOURBA"  
            ]},
   {gov:"Médenine", 
   cities:[]},
   {gov:"Monastir", 
   cities:[]},
   {gov:"Nabeul", 
   cities:[]},
   {gov:"Sfax", 
   cities:[]},
   {gov:"Sidi Bouzid", 
   cities:[]},
   {gov:"Siliana", 
   cities:[]},
   {gov:"Sousse", 
   cities:[]},
   {gov:"Tataouine", 
   cities:[]},
   {gov:"Tozeur", 
   cities:[]},
   {gov:"Tunis", 
   cities:[]},
   {gov:"Zaghouan", 
   cities:[]}
] 

// to access villes just write villes[gov] with gov variable or state from select option