export const SET_SELECTED_CENTER = "SET_SELECTED_CENTER"
export const FETCH_CENTERS_REQUEST = "FETCH_CENTERS_REQUEST"
export const FETCH_CENTERS_SUCCESS = "FETCH_CENTERS_SUCCESS"
export const FETCH_CENTERS_FAILURE = "FETCH_CENTERS_FAILURE"

export const FETCH_CENTER_BY_ID = "FETCH_CENTER_BY_ID"
export const ADD_CENTER="ADD_CENTER"
export const UPDATE_CENTER="UPDATE_CENTER"
export const DELETE_CENTER="DELETE_CENTER"